[package]
name = "day-06"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
ilog = "1.0.1"

[dev-dependencies]
rstest = { version = "0.18.2", default_features = false }
